[package]
name = "miniscript"
version = "0.8.0"
authors = ["Andrew Poelstra <apoelstra@wpsoftware.net>"]
repository = "https://github.com/apoelstra/miniscript"
description = "Miniscript: a subset of Bitcoin Script designed for analysis"
license = "CC0-1.0"

[features]
fuzztarget = ["bitcoin/fuzztarget"]
compiler = []
trace = []
unstable = []
default = []

[dependencies]
bitcoin = "0.19"

[dependencies.serde]
version = "1.0"
optional = true

