[package]
name = "miniscript"
version = "0.1.0"
authors = ["Andrew Poelstra <apoelstra@wpsoftware.net>"]

[features]
fuzztarget = ["secp256k1/fuzztarget"]
trace = []
unstable = []

[dependencies]
bitcoin = "0.15"
arrayvec = "0.4"

[dependencies.secp256k1]
version = "0.11"

