[package]
name = "script_descriptor"
version = "0.1.0"
authors = ["Andrew Poelstra <apoelstra@wpsoftware.net>"]


[[bin]]
name = "compile_all"
path = "src/compile_all.rs"

[[bin]]
name = "satisfy_all"
path = "src/satisfy_all.rs"

[features]
fuzztarget = ["secp256k1/fuzztarget"]
unstable = []

[dependencies]
secp256k1 = "0.10"

[dependencies.bitcoin]
version = "0.13"
path = "../rust-bitcoin/"
